language: python

sudo: required
dist: trusty

env:
  - OS_TYPE=debian8
  - OS_TYPE=debian9
  - OS_TYPE=ubuntu16.04

services:
  - docker

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "nightly"
    
before_install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh

before_script:
  - docker build -t ndts .travis/${OS_TYPE}
  - docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
  - .travis/install.sh ${OS_TYPE}

script:
  - .travis/run.sh

after-script:
  - docker stop ndts
  - docker rm ndts
