language: python
dist: xenial

env:
  - OS=debian10 PY=3
  - OS=debian10 PY=2
  - OS=debian9 PY=3
  - OS=debian9 PY=2
  - OS=debian8 PY=3
  - OS=debian8 PY=2
  - OS=ubuntu18.04 PY=3
  - OS=ubuntu18.04 PY=2
  - OS=ubuntu16.04 PY=2
#   - OS=ubuntu16.04 PY=3

services:
  - docker

before_install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh

before_script:
  - docker build -t ndts .travis/${OS}_py${PY}
  - docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
  - .travis/install.sh ${OS} ${PY}

script:
  - .travis/run.sh ${PY}

after-script:
  - docker stop ndts
  - docker rm ndts
