language: python

sudo: required
dist: trusty

env:
  - OS_TYPE=debian9 PYTHON=3
  - OS_TYPE=debian9 PYTHON=2
  - OS_TYPE=debian8 PYTHON=3
  - OS_TYPE=debian8 PYTHON=2
  - OS_TYPE=ubuntu18.04 PYTHON=3
  - OS_TYPE=ubuntu18.04 PYTHON=2
  - OS_TYPE=ubuntu16.04 PYTHON=2
#   - OS_TYPE=ubuntu16.04 PYTHON=3

services:
  - docker

before_install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh

before_script:
  - docker build -t ndts .travis/${OS_TYPE}_py${PYTHON}
  - docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
  - .travis/install.sh ${OS_TYPE} ${PYTHON}

script:
  - .travis/run.sh ${PYTHON}

after-script:
  - docker stop ndts
  - docker rm ndts
